<?php
/**
 * Asset registration service.
 *
 * @package MotionForWP
 */

declare( strict_types=1 );

namespace MotionForWP;

use MotionForWP\Content\Catalog;
use MotionForWP\Contracts\Service;
use MotionForWP\Settings\Options;

/** Registers frontend and editor assets. */
final class Assets implements Service {
	/**
	 * Animation catalog.
	 *
	 * @var Catalog
	 */
	private $catalog;

	/**
	 * Option repository.
	 *
	 * @var Options
	 */
	private $options;

	/**
	 * Creates the asset service.
	 *
	 * @param Catalog $catalog Animation catalog.
	 * @param Options $options Option repository.
	 */
	public function __construct( Catalog $catalog, Options $options ) {
		$this->catalog = $catalog;
		$this->options = $options;
	}

	/**
	 * Registers WordPress hooks.
	 */
	public function register(): void {
		add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_front_assets' ) );
		add_action( 'enqueue_block_editor_assets', array( $this, 'enqueue_editor_assets' ) );
	}

	/**
	 * Enqueues frontend animation assets.
	 */
	public function enqueue_front_assets(): void {
		$asset = $this->get_script_asset( 'dist/js/app.asset.php' );

		wp_enqueue_style(
			'motion-for-wp-style',
			MOTION_FOR_WP_URL . 'dist/css/front.css',
			array(),
			$this->asset_version( 'dist/css/front.css' )
		);

		wp_enqueue_script(
			'motion-for-wp-script',
			MOTION_FOR_WP_URL . 'dist/js/app.js',
			$asset['dependencies'],
			$asset['version'],
			true
		);

		$this->add_runtime_data( 'motion-for-wp-script' );
	}

	/**
	 * Enqueues block editor extensions only in the block editor.
	 */
	public function enqueue_editor_assets(): void {
		$asset = $this->get_script_asset( 'dist/js/admin.asset.php' );

		wp_enqueue_style(
			'motion-for-wp-admin-style',
			MOTION_FOR_WP_URL . 'dist/js/admin.css',
			array( 'wp-components' ),
			$this->asset_version( 'dist/js/admin.css' )
		);

		wp_enqueue_script(
			'motion-for-wp-admin-script',
			MOTION_FOR_WP_URL . 'dist/js/admin.js',
			$asset['dependencies'],
			$asset['version'],
			true
		);

		$this->add_runtime_data( 'motion-for-wp-admin-script' );
		wp_set_script_translations( 'motion-for-wp-admin-script', 'motion-for-wp', MOTION_FOR_WP_PATH . 'languages' );
	}

	/**
	 * Adds immutable runtime configuration before a script.
	 *
	 * @param string $handle Registered script handle.
	 */
	private function add_runtime_data( string $handle ): void {
		$data = array(
			'animations'     => $this->catalog->get_animations(),
			'easings'        => $this->catalog->get_easings(),
			'options'        => $this->options->get(),
			'excludedBlocks' => $this->get_excluded_blocks(),
		);

		$encoded_data = wp_json_encode( $data );

		wp_add_inline_script(
			$handle,
			'window.motionForWP = ' . $encoded_data . ';' .
			'window.motionForWPAnimations = window.motionForWP.animations;' .
			'window.motionForWPEasings = window.motionForWP.easings;' .
			'window.motionForWPOptions = window.motionForWP.options;',
			'before'
		);
	}

	/**
	 * Returns block types excluded from Motion controls by default.
	 *
	 * @return array<int, string>
	 */
	private function get_excluded_blocks(): array {
		$excluded_blocks = array(
			'core/freeform',
			'core/html',
			'core/legacy-widget',
			'core/missing',
			'core/shortcode',
			'core/widget-area',
		);

		/**
		 * Filters block types excluded from Motion controls.
		 *
		 * Dynamic blocks are excluded independently because they do not serialize
		 * a root element that can receive Motion's data attributes.
		 *
		 * @param array<int, string> $excluded_blocks Block names to exclude.
		 */
		$filtered = apply_filters( 'motion_for_wp/excluded_blocks', $excluded_blocks );

		if ( ! is_array( $filtered ) ) {
			return $excluded_blocks;
		}

		return array_values(
			array_unique(
				array_filter(
					array_map( 'sanitize_text_field', array_filter( $filtered, 'is_string' ) ),
					static function ( string $block_name ): bool {
						return 1 === substr_count( $block_name, '/' );
					}
				)
			)
		);
	}

	/**
	 * Returns a cache-busting asset version.
	 *
	 * @param string $relative_path Path relative to the plugin root.
	 */
	private function asset_version( string $relative_path ): string {
		$file_path = MOTION_FOR_WP_PATH . $relative_path;

		return is_readable( $file_path ) ? (string) filemtime( $file_path ) : MOTION_FOR_WP_VERSION;
	}

	/**
	 * Reads dependency metadata generated by WordPress Scripts.
	 *
	 * @param string $relative_path Asset metadata path relative to the plugin root.
	 * @return array{dependencies: array<int, string>, version: string}
	 */
	private function get_script_asset( string $relative_path ): array {
		$file_path = MOTION_FOR_WP_PATH . $relative_path;
		$fallback  = array(
			'dependencies' => array(),
			'version'      => MOTION_FOR_WP_VERSION,
		);

		if ( ! is_readable( $file_path ) ) {
			return $fallback;
		}

		$asset = require $file_path;

		if ( ! is_array( $asset ) || ! isset( $asset['dependencies'], $asset['version'] ) || ! is_array( $asset['dependencies'] ) ) {
			return $fallback;
		}

		return array(
			'dependencies' => array_values( array_filter( $asset['dependencies'], 'is_string' ) ),
			'version'      => (string) $asset['version'],
		);
	}
}
